name = "open-teleset"
main = "cloudflare-worker.js"
compatibility_date = "2024-11-01"
account_id = "c0e6bd9a7249856cb8497e7fe340e7ce"

[vars]
APP_ENV = "production"
SITE_URL = "https://open-teleset.site"
R2_BUCKET = "open-teleset"
R2_BUCKET_ASSETS = "open-teleset-assets"

[[kv_namespaces]]
binding = "CACHE"
id = "d47e93d92834409e925fd6b448b9c98a"

[[kv_namespaces]]
binding = "SESSIONS"
id = "b69ac10658364fcfbdf78eed1d4b7f2c"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "open-teleset"

[[r2_buckets]]
binding = "BUCKET_PROD"
bucket_name = "open-teleset-prod"

[[r2_buckets]]
binding = "BUCKET_ASSETS"
bucket_name = "open-teleset-assets"
